version: '2.0'

services:

  web:
    image: chialab/php-dev:7.4-apache
    build:
      context: docker/apache
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_autostart=1
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network
    depends_on:
      - database
    labels:
      - "traefik.docker.network=<<YOUR-TRAEFIK-NETWORK>>"
      # 新增一個 http 的
      - "traefik.http.routers.laravel-http.rule=Host(`laravel-dev.local`)"


  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel-network
    environment:
      MYSQL_ROOT_PASSWORD: YOUR-PASSWORD


networks:
  laravel-network:
    driver: bridge